#!/bin/bash
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --mem=48G
#SBATCH --cpus-per-task=4
#SBATCH --time=18:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=ndarmon@g.harvard.edu

# Per-task SLURM script for Sanctuary Phase 2 sweeps.
# Called by SLURM job array; each task reads its parameters from
# the task index file generated by submit_sweep.py.
#
# Environment variables set by submit_sweep.py:
#   SWEEP_DIR    -- directory containing task_index.tsv and sweep config
#   CONFIG_PATH  -- path to the base YAML config
#   SWEEP_NAME   -- sweep name for output directory organization

set -euo pipefail

echo "=== Sanctuary Phase 2 Task ==="
echo "SLURM_ARRAY_TASK_ID: ${SLURM_ARRAY_TASK_ID}"
echo "SWEEP_DIR: ${SWEEP_DIR}"
echo "CONFIG_PATH: ${CONFIG_PATH}"
echo "SWEEP_NAME: ${SWEEP_NAME}"

# Read task parameters from index file
TASK_LINE=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "${SWEEP_DIR}/task_index.tsv")
PROTOCOL=$(echo "$TASK_LINE" | cut -f1)
SEED=$(echo "$TASK_LINE" | cut -f2)

echo "Protocol: ${PROTOCOL}"
echo "Seed: ${SEED}"

# Activate Python environment
# Adjust this to match the cluster environment setup
if [ -f "${HOME}/sanctuary-env/bin/activate" ]; then
    source "${HOME}/sanctuary-env/bin/activate"
elif command -v conda &>/dev/null; then
    conda activate sanctuary 2>/dev/null || true
fi

# Ensure Ollama is running and models are available
if ! pgrep -x ollama >/dev/null 2>&1; then
    echo "Starting Ollama server..."
    ollama serve &
    sleep 10
fi

echo "Pulling models (no-op if already present)..."
ollama pull mistral-nemo:latest
ollama pull mistral-small:24b

# Run simulation
OUTPUT_DIR="runs/${SWEEP_NAME}/run_${PROTOCOL}_seed${SEED}"
echo "Output: ${OUTPUT_DIR}"
echo "Starting simulation..."

python3 -m sanctuary.run \
    --config "${CONFIG_PATH}" \
    --seed "${SEED}" \
    --output "${OUTPUT_DIR}" \
    --protocol "${PROTOCOL}"

echo "=== Task complete ==="
